In [ ]:
import numpy as np
a = np.array([5, 6, 7, 8])
a

In [6]:
b = np.arange(5, 100, 2)
b

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
       73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [7]:
c = np.linspace(5, 25, 4)
c


array([ 5.        , 11.66666667, 18.33333333, 25.        ])

In [8]:
m = np.array([[1,2,3,4], [5,6,7,8]])
m

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
m.shape

(2, 4)

In [18]:
doubled = m * 2
doubled

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [17]:
fours = doubled[doubled % 4 == 0]
fours

array([ 4,  8, 12, 16])

In [19]:
fours.shape

(4,)

In [25]:
n = np.arange(1, 16).reshape(3, 5, order = 'F')
n

array([[ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14],
       [ 3,  6,  9, 12, 15]])